### ISSUE TITLE
Implementation questions and notes

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p-circuit#2]
***WARNIG: Terminology is probably all wrong, so please feel free to correct.***

**Description**:

Implement a relay mechanism that allows connecting two otherwise unreachable hosts by establishing a tunnel/realy/circuit by a third, intermediary host (relay), that will forward packets/data on behalf of the two hosts.

According to a clarification by @hsanjuan - https://github.com/libp2p/specs/pull/8/files#diff-1f1a635913dabcb81c39fb105ecf053bR27:

> Unlike a transparent tunnel, where a libp2p peer would just proxy a communication stream to a destination (the destination being unaware of the original source), a circuit-relay makes the destination aware of the original source and the circuit followed to stablish communication between the two. This provides the destination side with the capacity of re-contacting the original source by rebuilding the circuit in the opposite direction, using the same relay.

**My current understanding of the flow**:

* Actors: `PeerA`, `PeerB`, `Relay`.
   * `PeerA` can speak WebRTC/WSS (js in browser)
   * `PeerB` can speak TCP/UDP (go node)
   * `Relay` can speak all of the above

*Simplest form*:
* `PeerA` wants a block that `PeerB` has
   * `PeerA` can't reach `PeerB` and tries to use one of the relays it knows about, 
      * picks `Relay`
   * `Relay` gets a request and tries to contact `PeerB`
      * protocol negotiation/selection and transfer happens over `multistream`

*Questions/Notes*:

1. Q: Besides having bootstrap relay nodes, how else would the peers find aditional relay nodes, is there already a mechanism for that.
   * A: Through the DHT and ...?
2. Q: Can the connection be reestablished from a destination peer to a source peer over any relay or does it have to be the same? (waiting for clarification in the spec - https://github.com/libp2p/specs/pull/8/files#r102636131)
3. Q: Are the proposed multiaddr combination formats (i.e. chaining) already supported or does multiaddr needs work to incorporate them?

**Implementation**:

According to this comment @lgierth - https://github.com/libp2p/go-libp2p/issues/82#issuecomment-272999400:

> So far I think the cleanest solution is to make the relay service a transport, so that we get end-to-end encryption -- the existing but unused relay code makes no attempt at that. It might at first feel weird that a swarm protocol is at the same time a transport, but this kind of stack hopping is what you sign up for when building overlay networks. It'll be something like: the RelayService calls Host.NewStream() and Host.SetStreamHandler(), and the Host calls RelayService.AddRelayPeer()

~~From what I see in the code, currently swarm already implements the transport interface, does that mean that that part has been already covered, or is this a different _swarm_?~~

**Implementation thoughts**:

~~~Looking at the js-libp2p-swarm, relay can (*should*?) be implemented as a transport, since as far as I can see the `interface-transport` allows for both, listens a connections/dials. The remark from @lgierth in the above comment is a little confusing, so some clarification is really welcome.~~~

~~~After some more consideration, I can see why what's @lgierth is proposing may make sense. Basically, the circuit transport has to be able to speak all the available protocols, which is some of what swarm encapsulates.~~~

@lgierth  @diasdavid  @dignifiedquire @whyrusleeping 
~~Can you outline in rough terms how would you go about implementing this?~~

**Performance considerations**:

Relaying packets/data  on a single process (nodejs) might not be scalable, a multiprocess solution might be required (node cluster), so concurrent access to the IPFS repo might need to be considered (if it isn't already).

-------------------------------------------------------------------------------

After talking to @lgierth, it now make more sense as to why the relay is both a swarm protocol, as in a protocol that utilizes the swarm, and a transport.

* It makes sense for the relay to be a swarm protocol because it can use it to dial into the destination peer
* It makes sense for it to be a transport, because it can both dial and listen on the /p2p/relay protocol

**Comment by lgierth** [comment]
> Q: Besides having bootstrap relay nodes, how else would the peers find aditional relay nodes, is there already a mechanism for that.
> A: Through the DHT and ...?

- "Accidental" discovery: right after establishing the connetion, peers exchange the protocols they support using the `identify` protocol. That means whenever we connect to someone who supports a relay protocol, we can use them as a relay.
- Service discovery: we'll eventually need a service discovery protocol, which facilitates finding nodes supporting a given protocol. (Similar to how content routing finds nodes holding a given content block.)
- There's no limits to creativity :)

Having a static list is the simplest for now.

> Q: Can the connection be reestablished from a destination peer to a source peer over any relay or does it have to be the same? (waiting for clarification in the spec - https://github.com/libp2p/specs/pull/8/files#r102636131)

It can be any relay which is able to communicate (share >=1 supported transport) with both the source and destination node.

> Q: Are the proposed multiaddr combination formats (i.e. chaining) already supported or does multiaddr needs work to incorporate them?

Multiaddr-wise, chaining is already possibel, since it's just an encapsulation of various kinds of addresses. The encapsulation/decapsulation part is built-in in multiaddr.

As for the actual relay protocol, I think we shouldn't bother too much with chaining for now. It's entirely possible that it's accidentally going to work right out of the box, but I imagine there will be weird little edge cases. After all it'd be putting *a lot of wrapping* around a stream, multiple stream muxers, etc. 

Regarding explicit addressing of the destination node, I think that's currently not easily possible. Swarm isn't able to do this explicit connection in one step. Instead, it first adds the new address to the peerbook entry for the respective destination node, and then dials that node's peerID. The dialing process will just use any address that works, but not neccessarily the one we specified. You can see this behaviour e.g. when passing full addresses to `ipfs swarm connect`.

**Comment by diasdavid** [comment]
@dryajov any question here left to answer?

**Comment by diasdavid** [comment]
Please refer to the spec from now on https://github.com/libp2p/specs/pull/22. Getting close :)
